---
Gemfile:
  optional:
    ':development':
      - gem: 'webmock'
      - gem: 'builder'
        version: '~> 3.2.2'
      - gem: 'puppet-resource_api'
        git: 'https://github.com/puppetlabs/puppet-resource_api.git'
        ref: 'master'
      # required for internal pipelines
      - gem: 'beaker-hostgenerator'
        # the first version to contain Palo Alto support
        version: '~> 1.1.15'
.gitignore:
  paths:
    - spec/fixtures/acceptance-credentials.conf
    - spec/fixtures/acceptance-device.conf
    - spec/fixtures/config-acceptance.xml
    - spec/fixtures/config-reset.xml
.pdkignore:
  paths:
    - spec/fixtures/acceptance-credentials.conf
    - spec/fixtures/acceptance-device.conf
    - spec/fixtures/config-acceptance.xml
    - spec/fixtures/config-reset.xml
Rakefile:
  requires:
    - 'puppet-strings/tasks'
spec/spec_helper.rb:
  mock_with: ':rspec'
  spec_overrides:
    - "require 'webmock/rspec'"
.travis.yml:
  simplecov: true
